# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Revised Integration Tests shared workflow
on:
  workflow_call:
    inputs:
      runtime_jdk:
        description: 'Which JDK version to use at runtime'
        required: false
        type: string
        default: 8
      use_indexer:
        description: 'Which indexer to use'
        required: false
        type: string
        default: indexer
      override_config_path:
        description: 'Existing Druid configuration (using Docker) can be overridden or new config vars can be set e.g. when using cloud storage'
        required: false
        type: string
      group:
        required: true
        type: string
        description: 'Name of group of tests running (to display)'
      testing_groups:
        required: true
        type: string
      build_jdk:
        description: 'Which jdk version was used to build'
        required: true
        type: string
      mysql_driver:
        description: 'MySQL driver to use'
        required: false
        type: string
        default: com.mysql.jdbc.Driver
      test_profile:
        description: 'Which IT test profile to run - (integration-tests or int-tests-config-file)'
        required: false
        type: string
        default: integration-tests
      config_file:
        description: 'Which config file to use'
        required: false
        type: string
      pod_name:
        description: 'To be used in case of k8s tests'
        required: false
        type: string
      pod_namespace:
        description: 'To be used in case of k8s tests'
        required: false
        type: string
      build_druid_cluster:
        description: 'To be used in case of k8s tests'
        required: false
        type: string

env:
  MVN: mvn --no-snapshot-updates
  MAVEN_SKIP: -P skip-static-checks -Dweb.console.skip=true -Dmaven.javadoc.skip=true
  MAVEN_SKIP_TESTS: -P skip-tests
  DOCKER_IP: 127.0.0.1  # for integration tests
  MYSQL_DRIVER_CLASSNAME: ${{ inputs.mysql_driver }}
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 5

jobs:
  test: # Github job that runs a given standard/old IT for a given testing group
    name: ${{ inputs.group }} integration test (Compile=jdk${{ inputs.build_jdk }}, Run=jdk${{ inputs.runtime_jdk }}, Indexer=${{ inputs.use_indexer }}, Mysql=${{ inputs.mysql_driver }})
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ inputs.runtime_jdk }}

      - name: Restore Maven repository
        id: maven-restore
        uses: actions/cache/restore@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ inputs.build_jdk }}-${{ github.sha }}
          fail-on-cache-miss: true

      - name: Run IT
        env:
          MYSQL_DRIVER_CLASSNAME: ${{ inputs.mysql_driver }}
          TEST_ARGS: |
            ${{ inputs.test_profile == 'integration-tests' &&
            format('-Djvm.runtime={0} -Dit.indexer={1} -Doverride.config.path={2}', inputs.runtime_jdk, inputs.use_indexer, inputs.override_config_path) ||
            format('-Dpod.name={0} -Dpod.namespace={1} -Dbuild.druid.cluster={2}',  inputs.pod_name, inputs.pod_namespace, inputs.build_druid_cluster) }}
        run: |
          # Debug echo
          echo "Mysql driver: ${MYSQL_DRIVER_CLASSNAME}"
          echo "MAVEN_OPTS='-Xmx2048m' ${MVN} verify -pl integration-tests -P ${{ inputs.test_profile }} ${{ inputs.testing_groups }} ${MAVEN_SKIP} ${TEST_ARGS}"
          MAVEN_OPTS='-Xmx2048m' ${MVN} verify -pl integration-tests -P ${{ inputs.test_profile }} ${{ inputs.testing_groups }} ${MAVEN_SKIP} ${TEST_ARGS}
